config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root 'static_pages#news' # Set root page as news.
  get 'solve-exercises', to: 'static_pages#exercises', as: 'static_exercises' # Solvable exercise list.
  get 'solutions/new/:id', to: 'solutions#new', as: 'new_solution' # New solution.
  get 'solutions/filter/:id', to: 'solutions#filter', as: 'filter_solution' # Filter solution

  resources :posts
  resources :solutions, except: [:new, :index]
  resources :exercises
  resources :year_categories
  resources :exercise_groups
  resources :user_levels
  devise_for :users
end

app/models/year_category.rb
class YearCategory < ApplicationRecord
end

app/controllers/year_categories_controller.rb
class YearCategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @year_categories = YearCategory.all.order('updated_at DESC')
  end

  def show
    # TODO
  end

  def new
    @year_category = YearCategory.new
  end

  def edit
    @year_category = YearCategory.find(params[:id])
  end

  def update
    @year_category = YearCategory.find(params[:id])
    if @year_category.update(year_category_params)
      flash[:success] = "Year Category was successfully edited!"
      redirect_to year_category_path(@year_category)
    else
      flash[:alert] = @year_category.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @year_category = YearCategory.find(params[:id])
    if @year_category.destroy
      flash[:success] = "Year Category was removed!"
    else
      flash[:error] = @year_category.errors.full_messages
    end
    redirect_to year_categories_path
  end

  def create
    @year_category = YearCategory.new(year_category_params)
    if @year_category.save
      flash[:success] = "Year Category has been created!"
      redirect_to year_categories_path
    else
      flash[:error] = @year_category.errors.full_messages
      redirect_to new_year_category_path
    end
  end

  private
    def year_category_params
      params.require(:year_category).permit(:title)
    end
end

app/helpers/year_categories_helper.rb
module YearCategoriesHelper
end

app/views/year_categories/_form_panel.html.erb
<div class="panel-body">
  <%= form_for @year_category do |f| %>
    <div class="field">
      <h3>Title</h3>
      <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "Title" %>
    </div></br>
</div>
<div class="panel-footer">
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
  </div>
</div>
<% end %>

app/views/year_categories/edit.html.erb
<div class="row">
    <div class="col-md-9">
      <div class ="panel panel-default">
          <div class="panel-heading"><h4>Edit Year Categories<h4></div>
            <%= render 'form_panel' %>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/year_categories/index.html.erb
<div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading"><h4>Manage Year Categories</h4></div>
        <div class="panel-body">
          <table class="table">
            <tbody>
              <% @year_categories.each do |year_category| %>
              <tr>
                <td>
                  <strong><%= link_to(year_category.title, edit_year_category_path(year_category)) %></strong> (<%= year_category.created_at %>)
                </td>
                <td>
                  <div class="text-right"><%= link_to("DELETE", year_category, data: { confirm: "You sure?" }, method: :delete) %></div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="panel-footer">
          <%= link_to(new_year_category_path) do %>
            <button class="btn btn-lg btn-primary btn-block">New Year Category</button>
          <% end %>
        </div>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/year_categories/new.html.erb
<div class="row">
    <div class="col-md-9">
      <div class ="panel panel-default">
          <div class="panel-heading"><h4>Create New Year Category<h4></div>
            <%= render 'form_panel' %>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/year_categories/show.html.erb
<div class="row">
    <div class="col-md-9">
      <div class="well">
        <h1>YearCategories#show</h1>
        <p>Find me in app/views/year_categories/show.html.erb</p>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>