config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root 'static_pages#news' # Set root page as news.
  get 'solve-exercises', to: 'static_pages#exercises', as: 'static_exercises' # Solvable exercise list.
  get 'solutions/new/:id', to: 'solutions#new', as: 'new_solution' # New solution.
  get 'solutions/filter/:id', to: 'solutions#filter', as: 'filter_solution' # Filter solution

  resources :posts
  resources :solutions, except: [:new, :index]
  resources :exercises
  resources :year_categories
  resources :exercise_groups
  resources :user_levels
  devise_for :users
end

app/models/user_level.rb
class UserLevel < ApplicationRecord
end

app/controllers/user_levels_controller.rb
class UserLevelsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_levels = UserLevel.all.order('updated_at DESC')
  end

  def show
    # TODO
  end

  def new
    @user_level = UserLevel.new
  end

  def edit
    @user_level = UserLevel.find(params[:id])
  end

  def update
    @user_level = UserLevel.find(params[:id])
    if @user_level.update(user_level_params)
      flash[:success] = "User level was successfully edited!"
      redirect_to user_level_path(@user_level)
    else
      flash[:alert] = @user_level.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @user_level = UserLevel.find(params[:id])
    if @user_level.destroy
      flash[:success] = "User Level was removed!"
    else
      flash[:error] = @user_level.errors.full_messages
    end
    redirect_to user_levels_path
  end

  def create
    @user_level = UserLevel.new(user_level_params)
    if @user_level.save
      flash[:success] = "User Level has been created!"
      redirect_to user_levels_path
    else
      flash[:error] = @user_level.errors.full_messages
      redirect_to new_user_level_path
    end
  end

  private
    def user_level_params
      params.require(:user_level).permit(:title, :level)
    end
end

app/helpers/user_levels_helper.rb
module UserLevelsHelper
end

app/views/user_levels/_form_panel.html.erb
<div class="panel-body">
  <%= form_for @user_level do |f| %>
    <div class="field">
      <h3>Title</h3>
      <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "Title" %>
    </div></br>
    <div class="field">
      <h3>Level</h3>
      <%= f.number_field :level, class: "form-control" %>
    </div></br>
</div>
<div class="panel-footer">
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
  </div>
</div>
<% end %>

app/views/user_levels/edit.html.erb
<div class="row">
    <div class="col-md-9">
      <div class ="panel panel-default">
          <div class="panel-heading"><h4>Edit User Levels<h4></div>
            <%= render 'form_panel' %>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/user_levels/index.html.erb
<div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading"><h4>Manage User Levels</h4></div>
        <div class="panel-body">
          <table class="table">
            <tbody>
              <% @user_levels.each do |user_level| %>
              <tr>
                <td>
                  <strong><%= link_to(user_level.title, edit_user_level_path(user_level)) %></strong> (<%= user_level.level %>)
                </td>
                <td>
                  <div class="text-right"><%= link_to("DELETE", user_level, data: { confirm: "You sure?" }, method: :delete) %></div>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="panel-footer">
          <%= link_to(new_user_level_path) do %>
            <button class="btn btn-lg btn-primary btn-block">New User Level</button>
          <% end %>
        </div>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/user_levels/new.html.erb
<div class="row">
    <div class="col-md-9">
      <div class ="panel panel-default">
          <div class="panel-heading"><h4>Create New User Level<h4></div>
            <%= render 'form_panel' %>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/user_levels/show.html.erb
<h1>UserLevels#show</h1>
<p>Find me in app/views/user_levels/show.html.erb</p>