config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root 'static_pages#news' # Set root page as news.
  get 'solve-exercises', to: 'static_pages#exercises', as: 'static_exercises' # Solvable exercise list.
  get 'solutions/new/:id', to: 'solutions#new', as: 'new_solution' # New solution.
  get 'solutions/filter/:id', to: 'solutions#filter', as: 'filter_solution' # Filter solution

  resources :posts
  resources :solutions, except: [:new, :index]
  resources :exercises
  resources :year_categories
  resources :exercise_groups
  resources :user_levels
  devise_for :users
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!

  def index
    @exercises = Exercise.all.order('updated_at DESC')
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def new
    @exercise = Exercise.new
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update(exercise_params)
      flash[:success] = "Exercise was edited successfully!"
      redirect_to exercise_path(@exercise)
    else
      flash[:alert] = @exercise.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    if @exercise.destroy
      flash[:success] = "Exercise was removed!"
    else
      flash[:error] = @exercise.errors.full_messages
    end
    redirect_to exercises_path
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      flash[:success] = "Exercise has been created!"
      redirect_to exercise_path(@exercise)
    else
      flash[:error] = @exercise.errors.full_messages
      redirect_to new_exercise_path
    end
  end

  private
    def exercise_params
      params.require(:exercise).permit(
        :title, :shorten, :description,
        exercise_tests_attributes: [:id, :test_input, :test_output, :_destroy])
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_exercise_test_fields.html.erb
<div class="row">
    <div class='nested-fields'>
        <div class="form-group col-xs-5">
            <%= f.input :test_input, label: false, :input_html => {:style=> 'height:70px;width: 100%;resize:none'}%>
        </div>
        <div class="form-group col-xs-5">
            <%= f.input :test_output, label: false, :input_html => {:style=> 'height:70px;width: 100%;resize:none'} %>
        </div>
        <div class="form-group col-xs-2">
          <%= link_to_remove_association f, class: 'btn btn-danger pull-right' do %>
            Remove
            <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </div>
    </div>
</div>

app/views/exercises/_form_panel.html.erb
<div class="panel-body">
  <%= simple_form_for @exercise do |f| %>
    <div class="field">
      <h3>Title</h3>
      <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "Title" %>
    </div></br>

    <div class="field">
      <h3>Short version</h3>
      <%= f.text_area :shorten,  class: "froala-editor", placeholder: "Short Description" %>
    </div></br>

    <div class="field">
      <h3>Description</h3>
      <%= f.text_area :description,  class: "froala-editor", placeholder: "Long Description" %>
    </div><br>

    <div class="row">
      <div class="form-group col-xs-5">
        <h3>Input</h3>
      </div>
      <div class="form-group col-xs-5">
        <h3>Output</h3>
      </div>
    </div>

    <div class="field">
      <%= f.simple_fields_for :exercise_tests do |exercise_test| %>
    	 <%= render 'exercise_test_fields', :f => exercise_test %>
    	<% end %>
      <%= link_to_add_association f, :exercise_tests, class: 'btn btn-info pull-left' do %>
        Add new Test
        <span class="glyphicon glyphicon-plus"></span>
      <% end %>
    </div>
</div>

<div class="panel-footer">
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
  </div>
</div>
<% end %>

app/views/exercises/edit.html.erb
<div class="row">
    <div class="col-md-9">
      <div class ="panel panel-default">
          <div class="panel-heading"><h4>Edit Exercise<h4></div>
            <%= render 'form_panel' %>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/exercises/index.html.erb
<div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading"><h4>Manage Exercises</h4></div>
        <div class="panel-body">
          <table class="table">
            <tbody>
              <% @exercises.each do |exercise| %>
              <tr>
                <td>
                  <strong><%= link_to(exercise.title, exercise_path(exercise)) %></strong> (<%= exercise.created_at %>)
                  <div class="fr-view"><%= exercise.shorten.html_safe %></div>
                </td>
                <td>
                  <%= link_to("DELETE", exercise, data: { confirm: "You sure?" }, method: :delete) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="panel-footer">
          <%= link_to(new_exercise_path) do %>
            <button class="btn btn-lg btn-primary btn-block">New Exercise</button>
          <% end %>
        </div>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/exercises/new.html.erb
<div class="row">
    <div class="col-md-9">
      <div class ="panel panel-default">
          <div class="panel-heading"><h4>Create New Post<h4></div>
            <%= render 'form_panel' %>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>

app/views/exercises/show.html.erb
<div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading"><h4><span class="glyphicon glyphicon-chevron-right"></span> <%= @exercise.title %></h4>
          <%= @exercise.get_status(current_user.id) %>
        </div>
        <div class="panel-body">
          <div class="fr-view"><%= @exercise.description.html_safe %></div>
        </div>
        <div class="panel-footer">
          <%= link_to new_solution_path(@exercise.id), class: "btn btn-primary" do %>
            Submit Solution <span class="glyphicon glyphicon-chevron-right"></span>
          <% end %>
          <div class="pull-right">
            <%= link_to filter_solution_path(@exercise.id), class: "btn btn-primary" do %>
               <span class="glyphicon glyphicon-chevron-left"></span> View Solutions
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'layouts/sidebar_static' %>
</div>