config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root 'static_pages#news' # Set root page as news.
  get 'solve-exercises', to: 'static_pages#exercises', as: 'static_exercises' # Solvable exercise list.
  get 'solutions/new/:id', to: 'solutions#new', as: 'new_solution' # New solution.
  get 'solutions/filter/:id', to: 'solutions#filter', as: 'filter_solution' # Filter solution

  resources :posts
  resources :solutions, except: [:new, :index]
  resources :exercises
  resources :year_categories
  resources :exercise_groups
  resources :user_levels
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_many :solutions
  has_many :exercise_tests
  accepts_nested_attributes_for :exercise_tests, reject_if: :all_blank, allow_destroy: true, allow_destroy: true
  before_save :default_values

  # Default values.
  def default_values
    self.solution_states ||= {}
  end

  # Returs exercise status by user id.
  def get_status(user_id)
    self.solution_states["#{user_id}"]
  end
end

app/models/exercise_group.rb
class ExerciseGroup < ApplicationRecord
end

app/models/exercise_test.rb
class ExerciseTest < ApplicationRecord
  belongs_to :exercise
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :exercise
  belongs_to :user
  before_save :default_values

  # Set default values.
  def default_values
    self.title ||= 'No title'
    self.error ||= ''
    self.time_limit ||= 10 # Seconds
    self.size_limit ||= 10 # MB
  end

  # Update exercise status which solution belongs to according to user id.
  def update_exercise_status
    status = self.exercise.solution_states[self.user_id]
    if status != "ok" # If solution is not solved, set status to the latest upload
      self.exercise.solution_states[self.user_id] = self.status
      self.exercise.save
      # TODO Add points to user
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :solutions
end

app/models/user_level.rb
class UserLevel < ApplicationRecord
end

app/models/year_category.rb
class YearCategory < ApplicationRecord
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!

  def index
    @exercises = Exercise.all.order('updated_at DESC')
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def new
    @exercise = Exercise.new
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update(exercise_params)
      flash[:success] = "Exercise was edited successfully!"
      redirect_to exercise_path(@exercise)
    else
      flash[:alert] = @exercise.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    if @exercise.destroy
      flash[:success] = "Exercise was removed!"
    else
      flash[:error] = @exercise.errors.full_messages
    end
    redirect_to exercises_path
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      flash[:success] = "Exercise has been created!"
      redirect_to exercise_path(@exercise)
    else
      flash[:error] = @exercise.errors.full_messages
      redirect_to new_exercise_path
    end
  end

  private
    def exercise_params
      params.require(:exercise).permit(
        :title, :shorten, :description,
        exercise_tests_attributes: [:id, :test_input, :test_output, :_destroy])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post was edited successfully!"
      redirect_to post_path(@post)
    else
      flash[:alert] = @post.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = "Post was removed!"
    else
      flash[:error] = @post.errors.full_messages
    end
    redirect_to posts_path
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post has been created!"
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      redirect_to new_post_path
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :shorten, :description)
    end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :authenticate_user!, except: [:json]

  # Show solution
  def show
    @solution = Solution.find(params[:id])
    @exercise = @solution.exercise
  end

  # Filter exercise solutions
  def filter
    @exercise = Exercise.find(params[:id])
    @solutions = Solution.where({ user_id: current_user.id, exercise_id: @exercise.id })
  end

  # New solution.
  def new
    @solution = Solution.new
    @exercise = Exercise.find(params[:id])
    session[:exercise_id] = params[:id]
  end

  # Create solution.
  def create
    uploaded_file = params[:solution_file]
    if uploaded_file
      exercise = Exercise.find(session[:exercise_id])

      @solution = Solution.new
      @solution.code = uploaded_file.read
      @solution.file_name_input = uploaded_file.original_filename
      @solution.file_name_output = @solution.file_name_input + '.out'
      @solution.exercise = exercise
      @solution.user = current_user
      @solution.language = 'c++'
      @solution.status = 'processing'

      if @solution.save
        flash[:success] = "Solution submitted successfully for #{exercise.title}!"
        # Request to solve the solution via background processing
        ConnectionWorker.perform_async(@solution.id)
        redirect_to exercise_path(session[:exercise_id])
      else
        flash[:notice] = "Solution submit failed!"
        redirect_to new_solution_path(session[:exercise_id])
      end
    else
      flash[:notice] = "File error!"
      redirect_to new_solution_path(session[:exercise_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_test_inputs(name)
    link_to name, '#', class: "add_test_inputs_fields", :"data-field" => "<p>
    <div class=\"pull-left\"><input class='text optional' type='text'  name='exercise[test_inputs][]' id='exercise_'></div>
    <div class=\"pull-right\">TEST</div></p><hr>"
  end
end

app/helpers/exercise_groups_helper.rb
module ExerciseGroupsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/user_levels_helper.rb
module UserLevelsHelper
end

app/helpers/year_categories_helper.rb
module YearCategoriesHelper
end

app/views/layouts/_footer.html.erb
<hr>
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Ugnius Skučas <%= Time.now.year %></p>
        </div>
        <%= params.inspect %>
    </div>
</footer>

app/views/layouts/_logo.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="well">
        <img class="img-responsive" src="http://placehold.it/900x200" alt="">
    </div>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to(root_url, class: "navbar-brand") do %>
              <%= fa_icon "laptop" %> Title
            <% end %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li>
                <%= link_to("Exercises", static_exercises_path) %>
              </li>
              <li>
                  <a href="#">About</a>
              </li>
          </ul>
            <ul class="nav navbar-nav pull-right">
                <% if current_user %>
                  <li>
                    <%= link_to(destroy_user_session_path, :method => :delete) do %>
                      <%= fa_icon "lock", text: "Logout" %>
                    <% end %>
                  </li>
                <% end %>
            </ul>
        </div>
         <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_sidebar_static.html.erb
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-3">
  <% if !user_signed_in? %>
    <%= render 'panels/login' %>
  <% else %>
    <%= render 'panels/admin_menu' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ktupvs</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <%= render 'layouts/navbar' %>
  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info", id: "alert_message") %>
      <% end %>
      <%= render 'layouts/logo' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/panels/_admin_menu.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h4><%= fa_icon "bars" %> Content Menu</h4></div>
  <div class="panel-body">
    <p><span class="glyphicon glyphicon-chevron-right"></span> <%= link_to("Manage Posts", posts_path) %></p>
    <p><span class="glyphicon glyphicon-chevron-right"></span> <%= link_to("Manage Exercises", exercises_path) %></p>
    <p><span class="glyphicon glyphicon-chevron-right"></span> <%= link_to("Manage User Levels", user_levels_path) %></p>
    <p><span class="glyphicon glyphicon-chevron-right"></span> <%= link_to("Manage Year Categories", year_categories_path) %></p>
    <p><span class="glyphicon glyphicon-chevron-right"></span> <%= link_to("Manage Exercise Groups", exercise_groups_path) %></p>
  </div>
  <div class="panel-footer">
  </div>
</div>

app/views/panels/_login.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h4>Login</h4></div>
  <div class="panel-body">
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
      </div>

      <div class="field">
        <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
      </div>
      <%= render "devise/shared/links" %>
  </div>
  <div class="panel-footer">
    <div class="actions">
      <%= f.submit "Log in", class: "btn btn-lg btn-primary btn-block" %>
    </div>
  </div>
    <% end %>
</div>